server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8

spring:
  cloud:
    gateway:
      routes:
        - id: before_route
          uri: lb://special-service:7000
          predicates:
            - Path=/special/**

        - id: path_route
          uri: lb://content-service:7001
          predicates:
            - Path=/content/**

          filters:
            - PrefixPath=/special
  application:
    name: my-gateway


eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:9001/eureka